Parameters:
  Email:
    Description: Email to include in the topic subscription list
    Type: String

Resources:
  MyQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MySampleQueue1
      DelaySeconds: 3
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 600
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: Encrypted queues require extra steps when configuring CMKs (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-key-management.html#compatibility-with-aws-services)

  MyQueue2:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MySampleQueue2
      MaximumMessageSize: 262144
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 300
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: Encrypted queues require extra steps when configuring CMKs (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-key-management.html#compatibility-with-aws-services)

  MyQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref MyQueue1, !Ref MyQueue2]
      PolicyDocument:
        Id: MyQueuePolicy
        Statement:
          - Sid: Allow-SendMessage-To-Both-Queues-From-SNS-Topic
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "SQS:SendMessage"
            Resource: "*"
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref MySnsTopic
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F21
            reason: Policy uses condition to limit access from SNS topic

  MySnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Sample topic that sends messages to two SQS queues
      TopicName: FanoutTopic
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !GetAtt MyQueue1.Arn
          Protocol: sqs
        - Endpoint: !GetAtt MyQueue2.Arn
          Protocol: sqs
        - Endpoint: !Ref Email
          Protocol: email

Outputs:
  Queue1URL:
    Value: !Ref MyQueue1
  Queue2URL:
    Value: !Ref MyQueue2
  TopicArn:
    Value: !Ref MySnsTopic
