Parameters:
  InstanceType:
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  KeyPair:
    Description: Key pair to connect to the instances
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    Description: Ip address allowed to SSH into the instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: "0.0.0.0/0"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
  Email:
    Description: Email to send notifications for this environment
    Type: String

Mappings: 
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-logging-bucket-permissions
  ELBAccountIdMap: 
    us-east-1:
      Id: 127311923021
    eu-west-1:
      Id: 156460612806
    us-west-2: 
      Id: 797873946194

Resources:
  MyApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: MyApplication
      ResourceLifecycleConfig:
        ServiceRole: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":role/aws-elasticbeanstalk-service-role"]]
        VersionLifecycleConfig:
          MaxCountRule:
            DeleteSourceFromS3: true
            Enabled: true
            MaxCount: 5

  AccessLogS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  AccessLogS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: [!FindInMap [ELBAccountIdMap, !Ref "AWS::Region", Id]]
            Action: s3:PutObject
            Resource: !Join ["", ["arn:aws:s3:::", !Ref AccessLogS3Bucket, "/*"]]
      Bucket: !Ref AccessLogS3Bucket

  MyEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref MyApplication
      EnvironmentName: MyEnvironment
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.12.2 running Docker 18.03.1-ce
      Tier:
        Name: WebServer
        Type: Standard
      
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
      OptionSettings:
        - Namespace: "aws:autoscaling:asg"
          OptionName: MinSize
          Value: 1
        - Namespace: "aws:autoscaling:asg"
          OptionName: MaxSize
          Value: 3

        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: IamInstanceProfile
          Value: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":instance-profile/aws-elasticbeanstalk-ec2-role"]]
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: InstanceType
          Value: !Ref InstanceType
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: EC2KeyName
          Value: !Ref KeyPair
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: SSHSourceRestriction
          Value: !Join [",", ["tcp", "22", "22", !Ref SSHLocation]]

        - Namespace: "aws:autoscaling:updatepolicy:rollingupdate"
          OptionName: RollingUpdateEnabled
          Value: true
        - Namespace: "aws:autoscaling:updatepolicy:rollingupdate"
          OptionName: RollingUpdateType
          Value: Health

        - Namespace: "aws:elasticbeanstalk:application"
          OptionName: Application Healthcheck URL
          Value: /hc
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: MY_SAMPLE_PROP
          Value: MY_SAMPLE_VALUE

        - Namespace: "aws:elasticbeanstalk:cloudwatch:logs"
          OptionName: StreamLogs
          Value: true
        - Namespace: "aws:elasticbeanstalk:cloudwatch:logs"
          OptionName: DeleteOnTerminate
          Value: true
        - Namespace: "aws:elasticbeanstalk:cloudwatch:logs"
          OptionName: RetentionInDays
          Value: 30

        - Namespace: "aws:elasticbeanstalk:cloudwatch:logs:health"
          OptionName: HealthStreamingEnabled
          Value: true
        - Namespace: "aws:elasticbeanstalk:cloudwatch:logs:health"
          OptionName: DeleteOnTerminate
          Value: true
        - Namespace: "aws:elasticbeanstalk:cloudwatch:logs:health"
          OptionName: RetentionInDays
          Value: 14

        - Namespace: "aws:elasticbeanstalk:command"
          OptionName: DeploymentPolicy
          Value: Rolling
        - Namespace: "aws:elasticbeanstalk:command"
          OptionName: BatchSizeType
          Value: Fixed
        - Namespace: "aws:elasticbeanstalk:command"
          OptionName: BatchSize
          Value: 1

        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: ServiceRole
          Value: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":role/aws-elasticbeanstalk-service-role"]]
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: LoadBalancerType
          Value: application
        - Namespace: "aws:elasticbeanstalk:environment:process:default"
          OptionName: HealthCheckPath
          Value: /hc
        - Namespace: "aws:elasticbeanstalk:environment:process:default"
          OptionName: HealthyThresholdCount
          Value: 2
        - Namespace: "aws:elasticbeanstalk:environment:process:default"
          OptionName: UnhealthyThresholdCount
          Value: 2

        - Namespace: "aws:elasticbeanstalk:healthreporting:system"
          OptionName: SystemType
          Value: enhanced

        - Namespace: "aws:elasticbeanstalk:hostmanager"
          OptionName: LogPublicationControl
          Value: true

        - Namespace: "aws:elasticbeanstalk:managedactions"
          OptionName: ManagedActionsEnabled
          Value: true
        - Namespace: "aws:elasticbeanstalk:managedactions"
          OptionName: PreferredStartTime
          Value: "Tue:22:00"
        - Namespace: "aws:elasticbeanstalk:managedactions:platformupdate"
          OptionName: UpdateLevel
          Value: minor
        - Namespace: "aws:elasticbeanstalk:managedactions:platformupdate"
          OptionName: InstanceRefreshEnabled
          Value: true

        - Namespace: "aws:elbv2:loadbalancer"
          OptionName: AccessLogsS3Bucket
          Value: !Ref AccessLogS3Bucket
        - Namespace: "aws:elbv2:loadbalancer"
          OptionName: AccessLogsS3Enabled
          Value: true

        - Namespace: "aws:elasticbeanstalk:sns:topics"
          OptionName: Notification Endpoint
          Value: !Ref Email

Outputs:
  EndPoint:
    Value: !GetAtt MyEnvironment.EndpointURL
