Parameters:
  ServiceRoleArn:
    Type: String
    Description: The ARN of the service role that AWS CodeBuild uses to interact with other services

Resources:
  MyRepositoryTriggerTopic:
    Type: AWS::SNS::Topic
  MyRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyAppRepository
      Triggers:
        - Name: DefaultTrigger
          CustomData: Some custom data
          DestinationArn: !Ref MyRepositoryTriggerTopic
          Branches: [master]
          Events: [all]

  MyArtifactsBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  MyBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MyAppBuildProject
      TimeoutInMinutes: 10
      ServiceRole: !Ref ServiceRoleArn
      Source:
        Location: !GetAtt MyRepository.CloneUrlHttp
        Type: CODECOMMIT
        GitCloneDepth: 1
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/dot-net:core-2.1
      Artifacts:
        Name: app-artifacts.zip
        NamespaceType: BUILD_ID
        Location: !Ref MyArtifactsBucket
        Packaging: ZIP
        Type: S3

Outputs:
  RepositoryCloneUrl:
    Value: !GetAtt MyRepository.CloneUrlHttp
