Parameters:
  ApplicationName:
    Type: String
    MaxLength: 50
  MinHealthyHostsType:
    Type: String
    Default: FLEET_PERCENT
    AllowedValues:
      - FLEET_PERCENT
      - HOST_COUNT
  MinHealthyHostsValue:
    Type: Number
    Default: 50
    MinValue: 1

Resources:
  MyApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      ComputePlatform: Server

  MyDeploymentConfig:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties:
      DeploymentConfigName: !Join ["-", [!Ref ApplicationName, "DeploymentConfig"]]
      MinimumHealthyHosts:
        Type: !Ref MinHealthyHostsType
        Value: !Ref MinHealthyHostsValue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Application name is passed as a parameter

  MyTriggerStatusTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns

  MyDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: MyApplication
    Properties:
      ApplicationName: !Ref ApplicationName
      DeploymentConfigName: !Ref MyDeploymentConfig
      DeploymentGroupName: !Join ["-", [!Ref ApplicationName, "DeploymentGroup"]]
      ServiceRoleArn: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":role/CodeDeployServiceRole"]]
      Ec2TagFilters:
        - Key: Name
          Value: CodeDeployInstance
          Type: KEY_AND_VALUE
      AutoRollbackConfiguration:
        Enabled: true
        Events: [DEPLOYMENT_FAILURE, DEPLOYMENT_STOP_ON_REQUEST]
      TriggerConfigurations:
        - TriggerName: DeploymentStatusTrigger
          TriggerTargetArn: !Ref MyTriggerStatusTopic
          TriggerEvents: [DeploymentFailure, DeploymentSuccess, DeploymentRollback, InstanceFailure]
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Application name is passed as a parameter

Outputs:
  ApplicationArn:
    Description: A reference to the CodeDeploy application
    Value: !Ref MyApplication
