Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: sample-repository
      LifecyclePolicy:
        LifecyclePolicyText: '{ "rules": [{ "rulePriority": 1, "description": "Expire images older than 14 days", "selection": { "tagStatus": "untagged", "countType": "sinceImagePushed", "countUnit": "days", "countNumber": 14 }, "action": { "type": "expire" } }] }'
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: 
                - !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":user/bob"]]
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

Outputs:
  RepositoryArn:
    Value: !GetAtt MyRepository.Arn
