Description: Task definition based on https://github.com/aws-samples/ecs-refarch-cloudformation

Parameters:
  ImageUrl:
    Type: String
    Description: Url for the image this task definition will use

Resources:
  MyTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: product-service
      ContainerDefinitions:
        - Name: product-service
          Essential: true
          Image: !Ref ImageUrl
          Memory: 128
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AWS::StackName
              awslogs-region: !Ref AWS::Region

Outputs:
  TaskDefinitionArn:
    Value: !Ref MyTaskDef
