Parameters:
  AdminPassword:
    Type: String
    MinLength: 8
    NoEcho: true
  DirectorySize:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Large
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  MyActiveDirectory:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      CreateAlias: true
      Description: My test simple AD
      EnableSso: true
      Name: corp.dscpinheiro.com
      Password: !Ref AdminPassword
      ShortName: CORP
      Size: !Ref DirectorySize
      VpcSettings:
        VpcId: !Ref VpcId
        SubnetIds: !Ref SubnetIds

Outputs:
  DirectoryId:
    Value: !Ref MyActiveDirectory
