Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.200.0.0/16"

      # Amazon DNS server resolves DNS hostnames for instances to their corresponding IP addresses
      EnableDnsSupport: true

      # Instances in the VPC get DNS hostnames
      EnableDnsHostnames: true

      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: cloudformation-vpc

  SecondaryIpv4CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: "10.210.0.0/16"
  Ipv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref MyVpc
      AmazonProvidedIpv6CidrBlock: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: cloudformation-igw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVpc
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Value: !Ref MyVpc
  PrimaryCidrBlock:
    Value: !GetAtt MyVpc.CidrBlock
  SecondaryCidrBlock:
    Value: !Select [0, !GetAtt MyVpc.CidrBlockAssociations]
  Ipv6CidrBlock:
    Value: !Select [0, !GetAtt MyVpc.Ipv6CidrBlocks]
