Parameters:
  DefaultSecurityGroupId:
    Description: Id of the default security group, which will be allowed to access the clusters
    Type: AWS::EC2::SecurityGroup::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  MySubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: MySubnetGroup
      Description: Redis Subnet Group
      SubnetIds: !Ref Subnets
  MyParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis4.0
      Description: Custom parameter group for Redis

  MyCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.m4.large
      CacheParameterGroupName: !Ref MyParameterGroup
      CacheSubnetGroupName: !Ref MySubnetGroup
      ClusterName: MyCluster
      Engine: redis
      EngineVersion: 4.0.10
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !Ref DefaultSecurityGroupId
  MyReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      PrimaryClusterId: !Ref MyCluster
      AutomaticFailoverEnabled: true
      NumCacheClusters: 3
      ReplicationGroupDescription: My cluster replication group

Outputs:
  ClusterEndpoint:
    Value: !GetAtt MyCluster.RedisEndpoint.Address
  ReadEndpoints:
    Value: !GetAtt MyReplicationGroup.ReadEndPoint.Addresses
