# Service role has to be created first (https://stackoverflow.com/a/49808714/5181334):
# aws iam create-service-linked-role --aws-service-name es.amazonaws.com

Parameters:
  IdSubnet1:
    Type: AWS::EC2::Subnet::Id
  IdSubnet2:
    Type: AWS::EC2::Subnet::Id

Resources:
  MyESDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: true
        DedicatedMasterCount: 3
        DedicatedMasterType: t2.small.elasticsearch
        InstanceCount: 2
        ZoneAwarenessEnabled: true
        InstanceType: m4.large.elasticsearch
      ElasticsearchVersion: 6.0
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 15
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: 3
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "*"
      VPCOptions:
        SubnetIds:
          - !Ref IdSubnet1
          - !Ref IdSubnet2

Outputs:
  ClusterName:
    Description: Cluster name
    Value: !Ref MyESDomain
  ClusterDomainEndpoint:
    Description: Cluster domain endpoint
    Value: !GetAtt MyESDomain.DomainEndpoint
