Parameters:
  VpcId:
    Description: VPC this ASG will be launched into
    Type: AWS::EC2::VPC::Id
  AutoScalingGroupName:
    Type: String
    MinLength: 1
    MaxLength: 255
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    Type: String
    Default: t3.nano
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.large
  AmiId:
    Description: AMI id to use for this ASG
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  KeyPair:
    Description: Key pair to connect to the instances in the ASG
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    Description: Ip address allowed to SSH into instances in the ASG
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: "0.0.0.0/0"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable access via SSH and HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPair
      InstanceType: !Ref InstanceType
      SecurityGroups: [!Ref SecurityGroup]
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          yum -y install httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello from CloudFormation - ASG!" > /var/www/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroupName
      MinSize: '1'
      MaxSize: '3'
      VPCZoneIdentifier: !Ref Subnets
      LaunchConfigurationName: !Ref LaunchConfig
