Parameters:
  VpcId:
    Description: VPC this instance will be launched into
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Description: Subnet this instance will be launched into
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Type: String
    Default: t2.nano
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.large
  AmiId:
    Description: AMI id to use for this instance
    Type: AWS::EC2::Image::Id
    Default: ami-6cd6f714
  KeyPair:
    Description: Key pair to connect to this instance
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable access via SSH and HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPair
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "CF-${AWS::StackName}"
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          wget https://download.microsoft.com/download/1/f/7/1f7755c5-934d-4638-b89f-1f4ffa5afe89/aspnetcore-runtime-2.1.2-linux-x64.tar.gz
          mkdir -p $HOME/dotnet && tar zxf aspnetcore-runtime-2.1.2-linux-x64.tar.gz -C $HOME/dotnet
          export PATH=$PATH:$HOME/dotnet

Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
