Parameters:
  VpcId:
    Description: VPC this instance will be launched into
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Description: Subnet this instance will be launched into
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
  AmiId:
    Description: AMI id to use for this instance
    Type: AWS::EC2::Image::Id
    Default: ami-6cd6f714
  KeyPair:
    Description: Key pair to connect to this instance
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    Description: Ip address allowed to SSH into this instance
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: "0.0.0.0/0"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable access via SSH and HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPair
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "CF-${AWS::StackName}"
      UserData: 
        Fn::Base64: |
          #!/bin/bash -xe
          yum -y install httpd
          service httpd start
          chkconfig httpd on
          echo "Hello from CloudFormation!" > /var/www/html/index.html

Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
  PrivateDnsName:
    Value: !GetAtt Ec2Instance.PrivateDnsName
  PublicDnsName:
    Value: !GetAtt Ec2Instance.PublicDnsName
