Description: >
  Creates a bucket for logging purposes.
  It uses lifecyle rules to move files to cheaper storage, and has versioning and
  encryption enabled.

Resources:
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Id: TransitionAndExpire
          Status: Enabled
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
          NoncurrentVersionExpirationInDays: 45
          ExpirationInDays: 1095
          Transitions:
            - TransitionInDays: 30
              StorageClass: STANDARD_IA
            - TransitionInDays: 180
              StorageClass: GLACIER
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: Bucket is meant to be used for access logging
          - id: W51
            reason: Bucket does not require a bucket policy

Outputs:
  BucketName:
    Value: !Ref LogBucket
  BucketArn:
    Value: !GetAtt LogBucket.Arn
