Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join ["", ["arn:aws:s3:::", !Ref S3Bucket, "/*"]]
      Bucket: !Ref S3Bucket

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL # Website endpoint for the specified bucket
  S3BucketSecureURL:
    Value: !Join ["", ["https://", !GetAtt S3Bucket.DomainName]] # IPv4 DNS name of the bucket
