Parameters:
  UserName:
    Description: The IAM username
    Type: String
    MinLength: 6
    MaxLength: 18
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  Groups:
    Description: Groups where this user should be included
    Type: CommaDelimitedList

Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      Groups: !Ref Groups
      UserName: !Ref UserName
