Parameters:
  VpcId:
    Description: VPC this ELB will be associated with
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  HostedZoneName:
    Description: Hosted zone in which the record sets will be created
    Type: String

Resources:
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable access via HTTP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
        Description: HTTP access
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F1000
            reason: All traffic outbound can be allowed
          - id: W2
            reason: Cidr is limited to port 80
          - id: W9
            reason: Cidr is limited to port 80
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W52
            reason: No access logging required
  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 80
      Protocol: HTTP
      LoadBalancerArn: !Ref LoadBalancer
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ELBTargetGroup
  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 5
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId

  RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ["", [!Ref HostedZoneName, .]]
      Comment: Zone apex alias targeted to a LoadBalancer
      RecordSets:
      - Name: !Join ["", [!GetAtt LoadBalancer.LoadBalancerName, ., !Ref "HostedZoneName", .]]
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
          DNSName: !GetAtt LoadBalancer.DNSName
