Parameters:
  KmsKeyId:
    Description: Key that will be used to encrypt the queue
    Default: alias/aws/sqs
    Type: String

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-encrypted-queue
      KmsMasterKeyId: !Ref KmsKeyId
      KmsDataKeyReusePeriodSeconds: 600
      ReceiveMessageWaitTimeSeconds: 20

Outputs:
  QueueURL:
    Value: !Ref MyQueue
