Parameters:
  KeyId:
    Description: Master key that will be used to create the encrypted volume
    Type: String
    Default: aws/ebs
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  VolumeSize:
    Type: Number
    Default: 10
    MinValue: 10
    MaxValue: 500
  VolumeType:
    Type: String
    Default: standard
    AllowedValues:
      - standard
      - gp2
      - sc1
      - st1

Resources:
  MyVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      AutoEnableIO: true
      Encrypted: true
      KmsKeyId: !Ref KeyId
      Size: !Ref VolumeSize
      VolumeType: !Ref VolumeType
      Tags:
        - Key: Name
          Value: my-encrypted-volume

Outputs:
  VolumeId:
    Value: !Ref MyVolume
