Parameters:
  MasterUsername:
    Type: String
  MasterUserPassword:
    Type: String
    MinLength: 12
    NoEcho: true
  DbInstanceClass:
    Type: String
    Default: db.r4.large
    AllowedValues:
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  Email:
    Description: Email to include in the events topic subscription list
    Type: String

Resources:
  MyCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    UpdateReplacePolicy: Snapshot
    Properties:
      AvailabilityZones: !GetAZs ""
      BackupRetentionPeriod: 10
      DatabaseName: MyCloudformationDB
      DBClusterIdentifier: my-cloudformation-cluster
      DBClusterParameterGroupName: !Ref MyClusterParameterGroup
      DBSubnetGroupName: !Ref MySubnetGroup
      Engine: aurora-mysql
      EngineMode: provisioned
      EngineVersion: 5.7.12
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      Port: 3306
      PreferredBackupWindow: 01:00-03:00
      PreferredMaintenanceWindow: sun:03:30-sun:05:30
      StorageEncrypted: true

  MyWriterInstance:
    Type: AWS::RDS::DBInstance
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBSubnetGroupName: !Ref MySubnetGroup
      DBParameterGroupName: !Ref MyDbParameterGroup
      DBClusterIdentifier: !Ref MyCluster
      DBInstanceClass: !Ref DbInstanceClass
      DBInstanceIdentifier: my-cloudformation-writer
      Engine: aurora-mysql
      PubliclyAccessible: false
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Instance identifier can be fixed
  MyReaderInstance:
    Type: AWS::RDS::DBInstance
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
    Properties:
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBSubnetGroupName: !Ref MySubnetGroup
      DBParameterGroupName: !Ref MyDbParameterGroup
      DBClusterIdentifier: !Ref MyCluster
      DBInstanceClass: !Ref DbInstanceClass
      DBInstanceIdentifier: my-cloudformation-reader
      Engine: aurora-mysql
      PubliclyAccessible: false
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Instance identifier can be fixed

  MySubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudFormation Sample Aurora Subnet Group
      SubnetIds: !Ref SubnetIds
  MyClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: CloudFormation Sample Aurora Cluster Parameter Group
      Family: aurora-mysql5.7
      Parameters:
        rds.force_ssl: 1
  MyDbParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: CloudFormation Sample Aurora Parameter Group
      Family: aurora-mysql5.7
      Parameters:
        log_statement: all

  EventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Topic for RDS events
      TopicName: RdsEventsTopic
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email
  EventSubscription:
    Type: AWS::RDS::EventSubscription
    Properties:
      Enabled: true
      SnsTopicArn: !Ref EventsTopic
      SourceIds:
        - !Ref MyWriterInstance
        - !Ref MyReaderInstance
      SourceType: db-instance

Outputs:
  ClusterEndpoint:
    Value: !GetAtt MyCluster.Endpoint.Address
  ClusterReadEndpoint:
    Value: !GetAtt MyCluster.ReadEndpoint.Address
  ClusterPort:
    Value: !GetAtt MyCluster.Endpoint.Port
