Resources:
  UserCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: user-credentials
      Description: This secret has a dynamically generated password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "masteruser"}'
        GenerateStringKey: 'password'
        PasswordLength: 64
        ExcludePunctuation: true
